openapi: 3.0.3
info:
  title: Demo Backend
  version: '1.0'
  description: |
    Demo Backend Login API
    
    See https://developer.truid.app/#_user_login_to_a_service
servers:
  - url: https://example.truid.app/
    description: example

paths:
  '/truid/v1/login-session':
    get:
      description: |
        Create an URL to use towards the Truid API to start the Login Session function
      parameters:
        - name: X-Requested-With
          description: |
            This header should be set if the client cannot handle manual redirect
            on 302 responses, and would rather want a 202 response.
          in: header
          required: false
          schema:
            type: string
            enum: [XMLHttpRequest]
      responses:
        '302':
          description: |
            Returning an URL that the client should redirect to in order to
            start a Truid Login Session function
          headers:
            Location:
              description: URL to redirect to for Truid Login Session function
              schema:
                type: string
        '202':
          description: |
            A 202 response is returned instead of a 302 response if the client
            is passing the header `X-Requested-With: XMLHttpRequest`. This is
            used because some clients cannot handle manual redirect on 302
            responses.
            
            A 202 response is to be treated exactly as a 302 response.
          headers:
            Location:
              description: URL to redirect to for Truid Login Session function
              schema:
                type: string
  '/truid/v1/complete-login':
    get:
      description: |
        Complete the signup flow.
        This is the endpoint that receives the OAuth2 authorization response.
        See https://www.rfc-editor.org/rfc/rfc6749#section-4.1.2
      parameters:
        - name: code
          description: |
            Code delivered in the authoization response.
            See https://www.rfc-editor.org/rfc/rfc6749#section-4.1.2
          in: query
          schema:
            type: string
        - name: state
          description: |
            State parameter from the authorization request.
            See https://www.rfc-editor.org/rfc/rfc6749#section-4.1.2
          in: query
          schema:
            type: string
        - name: error
          description: |
            Set to indicate an error in the authorization flow.
            See https://www.rfc-editor.org/rfc/rfc6749#section-4.1.2.1
          in: query
          schema:
            type: string
      responses:
        '200':
          description: |
            The Login Session was successful
        '403':
          description: |
            The signup flow failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompleteLoginSessionError'
  '/api/perform-action':
    post:
      description: |
        Example endpoint that requires that the user has an active login-session to be allowed to perform an action.
      responses:
        '200':
          description: |
            Current user is authenticated
        '401':
          description: |
            User is not authenticated

components:
  schemas:
    CompleteLoginSessionError:
      type: object
      properties:
        error:
          type: string
          enum: [invalid_request, invalid_client, invalid_grant, invalid_scope, unauthorized_client, unsupported_grant_type, access_denied, authentication_required]
          description: |
            See https://www.rfc-editor.org/rfc/rfc6749#section-4.1.2.1
      required: [ error ]
