name: PR Test

on:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # actions/checkout@v3.3.0
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Setup JDK
        # actions/setup-java@v2.5.1
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: maven

      - name: Verify
        working-directory: example-backend
        run: |
          ./mvnw --batch-mode verify
